front:
  build: .
  ports:
    - "80:80"
    - "443:443"
    # - "9000:9000"
  # links:
  #   - mysql:mysql
  #   - mongo:mongo
  #   - memcached:memcached
  #   - redis:redis
  #   - elasticsearch:elasticsearch
  #   - rabbitmq:rabbitmq
  environment:
    XDEBUG_CONFIG: remote_host=10.0.75.1
    # XDEBUG_CONFIG: remote_enable=on
    # XDEBUG_CONFIG: profiler_enable=on
    # XDEBUG_CONFIG: remote_port=9000
  volumes:
    - ./www:/var/www
    - ./sites:/etc/nginx/conf.d
    - ./logs/supervisor:/var/log/supervisor
    - ./logs/profiler:/var/log/profiler

# mysql:
#   image: mysql
#   ports:
#     - "3306:3306"
#   environment:
#     MYSQL_ROOT_PASSWORD: password

# mongo:
#   image: mongo
#   ports:
#     - "27017:27017"

# memcached:
#   image: memcached
#   ports:
#     - "11211:11211"

# redis:
#   image: redis
#   ports:
#     - "6379:6379"

# elasticsearch:
#   image: elasticsearch
#   ports:
#     - "9200:9200"
#     - "9300:9300"

# rabbitmq:
#   image: rabbitmq:3.6.1-management
#   ports:
#     - "15672:15672"
#     - "5672:5672"
